### ISSUE TITLE
CMTemperature crashes AU validation

### ISSUE THREAD

**Issue by lamech** [jatinchowdhury18/Bad-Circuit-Modelling#1]
Logic 10.5.1
OS X 10.15.7

On launching the Plug-In Manager and trying to validate the CMTemperature Audio Unit, the tests look like they pass, but at the end the plugin manager reports "crashed validation." I get the same results after restarting everything and rerunning validation. Output attached. 

All other "Bad Circuit Modelling" plugins seem to load fine.

Thanks!

[CMTemperature AU validation crash.txt](https://github.com/jatinchowdhury18/Bad-Circuit-Modelling/files/5660227/CMTemperature.AU.validation.crash.txt)

**Comment by jatinchowdhury18** [comment]
Ah, thanks for reporting this. Seems like it was just a typo on my end. Let me know if [these builds](https://github.com/jatinchowdhury18/Bad-Circuit-Modelling/blob/master/Bin/CMTemperature/MacBuilds.zip) work for you?

Thanks,
Jatin

**Comment by lamech** [comment]
Looks good, I was able to load and verify the AU in Logic.

Cheers!

**Comment by jatinchowdhury18** [comment]
Awesome, thanks!
